#
# Makefile for ls demos
#

all:	ls_demo1 ls_demo2

ls_demo1:	ls_demo1.o
	`ofeli-config --cxx` `ofeli-config --cflags` -o ls_demo1 ls_demo1.o `ofeli-config --libs`

ls_demo2:	ls_demo2.o
	`ofeli-config --cxx` `ofeli-config --cflags` -o ls_demo2 ls_demo2.o `ofeli-config --libs`



clean:
	/bin/rm -f *.o ls_demo1 ls_demo2

.cpp.o:
	`ofeli-config --cxx` `ofeli-config --cflags` -c $<

.c.o:
	`ofeli-config --cc` `ofeli-config --cflags` -c $<
