
all:	eigen_demo1 eigen_demo2

eigen_demo1:	eigen_demo1.o
	`ofeli-config --cxx` `ofeli-config --cflags` -o eigen_demo1 eigen_demo1.o `ofeli-config --libs`

eigen_demo2:	eigen_demo2.o
	`ofeli-config --cxx` `ofeli-config --cflags` -o eigen_demo2 eigen_demo2.o `ofeli-config --libs`

clean:
	/bin/rm -f *.o eigen_demo1 eigen_demo2


.cpp.o:
	`ofeli-config --cxx` `ofeli-config --cflags` -c $<

.c.o:
	`ofeli-config --cc` `ofeli-config --cflags` -c $<
