#! /bin/sh

prefix=/usr/local
exec_prefix=${prefix}
includedir=${prefix}/include
datadir=${prefix}/share
materialdir=$datadir/ofeli/material
docdir=$datadir/ofeli/doc

usage()
{
    cat << EOF
Usage: ofeli-config [OPTION]

Options:
  --prefix		show OFELI installation prefix 
  --exec_prefix		show OFELI exec prefix
  --libs		print library linking information
  --cflags		print compiler and pre-processor flags
  --exe_ext		executable files extension
  --cxx			c++ compiler
  --cc			c compiler
  --material            print material data path
  --data                print data file path
  --doc                 print doc file path
  --help		display this help and exit
  --version		output version information

EOF
    exit $1
}

if test $# -eq 0; then
    usage 1 1>&2
fi

cflags=false
includes=false
libs=false

while test $# -gt 0; do
    case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
    *) optarg= ;;
    esac

    case "$1" in
    --prefix=*)
	prefix=$optarg
	;;

    --prefix)
	echo $prefix
	;;

    --exec_prefix)
	echo $exec_prefix
	;;

    --cxx)
	echo g++
	;;

    --cc)
	echo gcc
	;;

    --version)
	echo 4.1.2
	;;

    --help)
	usage 0
	;;

    --cflags)
        echo -I${prefix}/include/ofeli -std=c++1y 
       	;;

    --data)
        echo $datadir
       	;;

    --material)
        echo $materialdir
       	;;

    --doc)
        echo $docdir
        ;;

    --exe_ext)
        echo 
        ;;

    --libs)
       	echo -lofeli  -lm -L${exec_prefix}/lib 
       	;;
    *)
	usage
	exit 1
	;;
    esac
    shift
done

exit 0
