
all:	transport

transport:	main.o
	`ofeli-config --cxx` `ofeli-config --cflags` -o transport main.o `ofeli-config --libs`

clean:
	/bin/rm -f main.o transport


.cpp.o:
	`ofeli-config --cxx` `ofeli-config --cflags` -c $<

.c.o:
	`ofeli-config --cc` `ofeli-config --cflags` -c $<
