
OBJ = main.o

all:	stdc2

stdc2:	$(OBJ)
	`ofeli-config --cxx` `ofeli-config --cflags` -o stdc2 $(OBJ) `ofeli-config --libs`

clean:
	/bin/rm -f $(OBJ) stdc2`ofeli-config --exe_ext`


.cpp.o:
	`ofeli-config --cxx` `ofeli-config --cflags` -c $<

.c.o:
	`ofeli-config --cc` `ofeli-config --cflags` -c $<
