
all:	lesson3

lesson3:	main.o
	`ofeli-config --cxx` `ofeli-config --cflags` -o lesson3 main.o `ofeli-config --libs`

clean:
	/bin/rm -f main.o lesson3`ofeli-config --exe_ext`


.cpp.o:
	`ofeli-config --cxx` `ofeli-config --cflags` -c $<

.c.o:
	`ofeli-config --cc` `ofeli-config --cflags` -c $<
