
all:	truss

truss:	main.o
	`ofeli-config --cxx` `ofeli-config --cflags` -o truss main.o `ofeli-config --libs`

clean:
	/bin/rm -f main.o truss`ofeli-config --exe_ext`

.cpp.o:
	`ofeli-config --cxx` `ofeli-config --cflags` -c $<

.c.o:
	`ofeli-config --cc` `ofeli-config --cflags` -c $<
