
OBJ = main.o

all:	tiff2

tiff2:	$(OBJ)
	`ofeli-config --cxx` `ofeli-config --cflags` -o tiff2 $(OBJ) `ofeli-config --libs`

clean:
	/bin/rm -f $(OBJ) tiff2`ofeli-config --exe_ext`


.cpp.o:
	`ofeli-config --cxx` `ofeli-config --cflags` -c $<

.c.o:
	`ofeli-config --cc` `ofeli-config --cflags` -c $<
