
all:	lesson2

lesson2:	main.o
	`ofeli-config --cxx` `ofeli-config --cflags` -o lesson2 main.o `ofeli-config --libs`

clean:
	/bin/rm -f main.o lesson2`ofeli-config --exe_ext`


.cpp.o:
	`ofeli-config --cxx` `ofeli-config --cflags` -c $<

.c.o:
	`ofeli-config --cc` `ofeli-config --cflags` -c $<
