
OBJ = main.o

all:	std3

std3:	$(OBJ)
	`ofeli-config --cxx` `ofeli-config --cflags` -o std3 $(OBJ) `ofeli-config --libs`

clean:
	/bin/rm -f $(OBJ) std3`ofeli-config --exe_ext`


.cpp.o:
	`ofeli-config --cxx` `ofeli-config --cflags` -c $<

.c.o:
	`ofeli-config --cc` `ofeli-config --cflags` -c $<
