
OBJ = main.o

all:	lh2d

lh2d:	$(OBJ)
	`ofeli-config --cxx` `ofeli-config --cflags` -o lh2d $(OBJ) `ofeli-config --libs`

clean:
	/bin/rm -f $(OBJ) lh2d`ofeli-config --exe_ext`


.cpp.o:
	`ofeli-config --cxx` `ofeli-config --cflags` -c $<

.c.o:
	`ofeli-config --cc` `ofeli-config --cflags` -c $<
