
OBJ = main.o

all:	euler-2d

euler-2d:	$(OBJ)
	`ofeli-config --cxx` `ofeli-config --cflags` -o euler-2d $(OBJ) `ofeli-config --libs`

clean:
	/bin/rm -f $(OBJ) euler-2d`ofeli-config --exe_ext`


.cpp.o:
	`ofeli-config --cxx` `ofeli-config --cflags` -c $<

.c.o:
	`ofeli-config --cc` `ofeli-config --cflags` -c $<
