
OBJ = main.o error.o

all:	stefan

stefan:	$(OBJ)
	`ofeli-config --cxx` `ofeli-config --cflags` -o ttd2 $(OBJ) `ofeli-config --libs`

clean:
	/bin/rm -f $(OBJ) ttd2`ofeli-config --exe_ext`


.cpp.o:
	`ofeli-config --cxx` `ofeli-config --cflags` -c $<

.c.o:
	`ofeli-config --cc` `ofeli-config --cflags` -c $<
