
all:	elliptic

elliptic:	main.o
	`ofeli-config --cxx` `ofeli-config --cflags` -o elliptic main.o `ofeli-config --libs`

clean:
	/bin/rm -f main.o elliptic


.cpp.o:
	`ofeli-config --cxx` `ofeli-config --cflags` -c $<

.c.o:
	`ofeli-config --cc` `ofeli-config --cflags` -c $<
