
OBJ = main.o

all:	lelas3d

lelas3d:	$(OBJ)
	`ofeli-config --cxx` `ofeli-config --cflags` -o lelas3d $(OBJ) `ofeli-config --libs`

clean:
	/bin/rm -f $(OBJ) lelas3d`ofeli-config --exe_ext` *.d beam-1.m

.cpp.o:
	`ofeli-config --cxx` `ofeli-config --cflags` -c $<

.c.o:
	`ofeli-config --cc` `ofeli-config --cflags` -c $<
