
all:	lesson4

ex4:	main.o
	`ofeli-config --cxx` `ofeli-config --cflags` -o lesson4 main.o `ofeli-config --libs`

clean:
	/bin/rm -f main.o lesson4`ofeli-config --exe_ext`


.cpp.o:
	`ofeli-config --cxx` `ofeli-config --cflags` -c $<

.c.o:
	`ofeli-config --cc` `ofeli-config --cflags` -c $<
