
OBJ = main.o User.o error.o

all:	helm

helm:	$(OBJ)
	`ofeli-config --cxx` `ofeli-config --cflags` -o Helmholtz $(OBJ) `ofeli-config --libs`

clean:
	/bin/rm -f $(OBJ) Helmholtz`ofeli-config --exe_ext`


.cpp.o:
	`ofeli-config --cxx` `ofeli-config --cflags` -c $<

.c.o:
	`ofeli-config --cc` `ofeli-config --cflags` -c $<
