#
# Makefile for linear programming demos
#

all:	lp_demo1

lp_demo1:	lp_demo1.o
	`ofeli-config --cxx` `ofeli-config --cflags` -o lp_demo1 lp_demo1.o `ofeli-config --libs`

clean:
	/bin/rm -f *.o lp_demo1

.cpp.o:
	`ofeli-config --cxx` `ofeli-config --cflags` -c $<

.c.o:
	`ofeli-config --cc` `ofeli-config --cflags` -c $<
